# Generated by Django 2.1.5 on 2019-02-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('headline', models.CharField(max_length=64)),
                ('story_cat', models.CharField(choices=[('pol', 'pol'), ('art', 'art'), ('tech', 'tech'), ('trivia', 'trivia')], max_length=6)),
                ('story_region', models.CharField(choices=[('uk', 'uk'), ('eu', 'eu'), ('w', 'w')], max_length=250)),
                ('story_date', models.DateTimeField(auto_now_add=True)),
                ('story_details', models.TextField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Author'),
        ),
    ]
